export const activityCodes = [
  { name: 'Aerobics', code: 9 },
  { name: 'Archery', code: 119 },
  { name: 'Badminton', code: 10 },
  { name: 'Baseball', code: 11 },
  { name: 'Basketball', code: 12 },
  { name: 'Biathlon', code: 13 },
  { name: 'Biking', code: 1 },
  { name: 'Handbiking', code: 14 },
  { name: 'Mountain biking', code: 15 },
  { name: 'Road biking', code: 16 },
  { name: 'Spinning', code: 17 },
  { name: 'Stationary biking', code: 18 },
  { name: 'Utility biking', code: 19 },
  { name: 'Boxing', code: 20 },
  { name: 'Calisthenics', code: 21 },
  { name: 'Circuit training', code: 22 },
  { name: 'Cricket', code: 23 },
  { name: 'Crossfit', code: 113 },
  { name: 'Curling', code: 106 },
  { name: 'Dancing', code: 24 },
  { name: 'Diving', code: 102 },
  { name: 'Elevator', code: 117 },
  { name: 'Elliptical', code: 25 },
  { name: 'Ergometer', code: 103 },
  { name: 'Escalator', code: 118 },
  { name: 'Fencing', code: 26 },
  { name: 'Football (American)', code: 27 },
  { name: 'Football (Australian)', code: 28 },
  { name: 'Football (Soccer)', code: 29 },
  { name: 'Frisbee', code: 30 },
  { name: 'Gardening', code: 31 },
  { name: 'Golf', code: 32 },
  { name: 'Gymnastics', code: 33 },
  { name: 'Handball', code: 34 },
  { name: 'HIIT', code: 114 },
  { name: 'Hiking', code: 35 },
  { name: 'Hockey', code: 36 },
  { name: 'Horseback riding', code: 37 },
  { name: 'Housework', code: 38 },
  { name: 'Ice skating', code: 104 },
  { name: 'In vehicle', code: 0 },
  { name: 'Interval Training', code: 115 },
  { name: 'Jumping rope', code: 39 },
  { name: 'Kayaking', code: 40 },
  { name: 'Kettlebell training', code: 41 },
  { name: 'Kickboxing', code: 42 },
  { name: 'Kitesurfing', code: 43 },
  { name: 'Martial arts', code: 44 },
  { name: 'Meditation', code: 45 },
  { name: 'Mixed martial arts', code: 46 },
  { name: 'On foot', code: 2 },
  { name: 'Other (unclassified fitness activity)', code: 108 },
  { name: 'P90X exercises', code: 47 },
  { name: 'Paragliding', code: 48 },
  { name: 'Pilates', code: 49 },
  { name: 'Polo', code: 50 },
  { name: 'Racquetball', code: 51 },
  { name: 'Rock climbing', code: 52 },
  { name: 'Rowing', code: 53 },
  { name: 'Rowing machine', code: 54 },
  { name: 'Rugby', code: 55 },
  { name: 'Running', code: 8, pointsModifier: 2 },
  { name: 'Jogging', code: 56 },
  { name: 'Running on sand', code: 57 },
  { name: 'Running (treadmill)', code: 58 },
  { name: 'Sailing', code: 59 },
  { name: 'Scuba diving', code: 60 },
  { name: 'Skateboarding', code: 61 },
  { name: 'Skating', code: 62 },
  { name: 'Cross skating', code: 63 },
  { name: 'Indoor skating', code: 105 },
  { name: 'Inline skating (rollerblading)', code: 64 },
  { name: 'Skiing', code: 65 },
  { name: 'Back-country skiing', code: 66 },
  { name: 'Cross-country skiing', code: 67 },
  { name: 'Downhill skiing', code: 68 },
  { name: 'Kite skiing', code: 69 },
  { name: 'Roller skiing', code: 70 },
  { name: 'Sledding', code: 71 },
  { name: 'Sleeping', code: 72 },
  { name: 'Light sleep', code: 109 },
  { name: 'Deep sleep', code: 110 },
  { name: 'REM sleep', code: 111 },
  { name: 'Awake (during sleep cycle)', code: 112 },
  { name: 'Snowboarding', code: 73 },
  { name: 'Snowmobile', code: 74 },
  { name: 'Snowshoeing', code: 75 },
  { name: 'Softball', code: 120 },
  { name: 'Squash', code: 76 },
  { name: 'Stair climbing', code: 77 },
  { name: 'Stair-climbing machine', code: 78 },
  { name: 'Stand-up paddleboarding', code: 79 },
  { name: 'Still (not moving)', code: 3 },
  { name: 'Strength training', code: 80 },
  { name: 'Surfing', code: 81 },
  { name: 'Swimming', code: 82 },
  { name: 'Swimming (open water)', code: 84 },
  { name: 'Swimming (swimming pool)', code: 83 },
  { name: 'Table tennis (ping pong)', code: 85 },
  { name: 'Team sports', code: 86 },
  { name: 'Tennis', code: 87 },
  { name: 'Tilting (sudden device gravity change)', code: 5 },
  { name: 'Treadmill (walking or running)', code: 88 },
  { name: 'Unknown (unable to detect activity)', code: 4 },
  { name: 'Volleyball', code: 89 },
  { name: 'Volleyball (beach)', code: 90 },
  { name: 'Volleyball (indoor)', code: 91 },
  { name: 'Wakeboarding', code: 92 },
  { name: 'Walking', code: 7, pointsModifier: 1.2 },
  { name: 'Walking (fitness)', code: 93 },
  { name: 'Nording walking', code: 94 },
  { name: 'Walking (treadmill)', code: 95 },
  { name: 'Walking (stroller)', code: 116 },
  { name: 'Waterpolo', code: 96 },
  { name: 'Weightlifting', code: 97 },
  { name: 'Wheelchair', code: 98 },
  { name: 'Windsurfing', code: 99 },
  { name: 'Yoga', code: 100 },
  { name: 'Zumba', code: 101 },
];

export function activityCodeToName(code: number) {
  const act = activityCodes.find(a => a.code === code);
  if (!act) {
    return 'Unknown activity';
  }
  return act.name;
}

export function getPointsModifier(code: number) {
  const act = activityCodes.find(a => a.code === code);
  if (!act || !act.pointsModifier) {
    return 1;
  }
  return act.pointsModifier;
}
