<template>
    <v-layout>
        <v-flex xs12 mt-4 sm8 offset-sm2>
            <v-card>
                <v-card-title>
                    <span class="mr-2">Account</span>
                    <v-icon>mdi-account-circle</v-icon>
                </v-card-title>
                <v-card-text>
                    <div>
                        <span
                            class="mr-2"
                        >
                            Nick
                        </span>
                        <span
                            class="ml-2"
                        >
                            Your nick here
                        </span>
                        <v-spacer></v-spacer>
                        <v-btn
                            flat
                            class="mx-0"
                            disabled
                        >
                        Edit
                        </v-btn>
                    </div>
                    <div>
                         <span
                            class="mr-2"
                        >
                            Email
                        </span>
                        <span
                            class="ml-2"
                        >
                            example@email.com
                        </span>
                        <v-spacer></v-spacer>
                        <v-btn
                            flat
                            class="mx-0"
                            disabled
                        >
                        Edit
                        </v-btn>
                    </div>
                     <div>
                         <span
                            class="mr-2"
                        >
                            Password
                        </span>
                        <span
                            class="ml-2"
                        >
                            ....
                        </span>
                        <v-spacer></v-spacer>
                        <v-btn
                            flat
                            class="mx-0"
                            disabled
                        >
                        Edit
                        </v-btn>
                    </div>
                </v-card-text>
            </v-card>
        </v-flex>
    </v-layout>
</template>